version: 2
registries:
  wp-packages:
    type: composer-repository
    url: https://repo.wp-packages.org
updates:
  - package-ecosystem: composer
    directory: "/"
    registries:
      - wp-packages
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "roots/wordpress"
        update-types: ["version-update:semver-major"]
    groups:
      wordpress-plugins:
        patterns: ["wp-plugin/*", "wp-theme/*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
