version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "roots/wordpress"
        update-types: ["version-update:semver-major"]
    groups:
      wordpress-plugins:
        patterns: ["wp-plugin/*", "wp-theme/*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
